---
# defaults file for configure-aap

aap_controller_namespace: ansible-automation-platform
aap_openshift_serviceaccount_name: aap-ocpv
aap_openshift_serviceaccount_token_name: "{{  aap_openshift_serviceaccount_name}}-token"
aap_credential_type_redhat_serviceaccount_name: Red Hat Service Account
aap_credential_type_publickey_name: SSH Public Key
aap_credential_type_redhat_csp_name: Red Hat Customer Portal
aap_credential_machine_name: OCPv SSH
aap_credential_jbossnetwork_name: JBossnetwork API
aap_credential_openshift_name: OCP
aap_credential_redhat_csp_name: RHN
aap_credential_openshift_host: https://kubernetes.default.svc
aap_credential_publickey_name: OCPv Public Key
aap_credential_automationhub_name: Automation Hub
aap_inventory_ocpv_name: ocpv
aap_inventory_ocpv_eap_name: eap

aap_template_deploy_ocp_playbook: playbooks/install-ocpv.yml
aap_template_deploy_lab_playbook: playbooks/deploy-lab.yml


aap_project_ocpv_name: ocpv_lab
aap_project_ocpv_git_url: https://github.com/ansible-middleware/ocpv_lab.git
aap_project_ocpv_git_branch: main

automationhub_server_url: "https://cloud.redhat.com/api/automation-hub/"
automationhub_auth_server_url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"

automationhub_token: ""

ocpv_ssh_user: cloud-user

aap_organization: Default

lab_namespace: ansible-middleware-ocpv
lab_name: eap-lab